# Generated by Django 5.0.9 on 2026-06-21 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkingScheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="marking_schemes/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PastPaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                (
                    "session",
                    models.CharField(
                        choices=[("june", "June"), ("november", "November")],
                        max_length=20,
                    ),
                ),
                ("paper_number", models.PositiveSmallIntegerField()),
                (
                    "paper_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("structured", "Structured"),
                            ("practical", "Practical"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="past_papers/")),
                (
                    "marking_scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="papers",
                        to="papers.markingscheme",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_papers",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "session"],
                "indexes": [
                    models.Index(
                        fields=["subject", "year", "paper_type"],
                        name="papers_past_subject_97d61c_idx",
                    )
                ],
            },
        ),
    ]
