# Generated by Django 5.2.15 on 2026-06-24 11:14

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markingscheme",
            name="file",
            field=models.FileField(
                upload_to="marking_schemes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    apps.common.validators.validate_upload_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pastpaper",
            name="file",
            field=models.FileField(
                upload_to="past_papers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    apps.common.validators.validate_upload_size,
                ],
            ),
        ),
    ]
