# Generated by Django 5.2.15 on 2026-09-15 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "phone_number_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("access_token_encrypted", models.TextField(blank=True, default="")),
                ("app_secret_encrypted", models.TextField(blank=True, default="")),
                ("verify_token_encrypted", models.TextField(blank=True, default="")),
                ("graph_api_version", models.CharField(default="v26.0", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
