# Generated by Django 5.2.15 on 2026-09-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0002_whatsappprovider"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappprovider",
            name="waba_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="WhatsApp Business Account ID (parent account; a WABA can own multiple phone numbers). Not required for sending/receiving messages -- only for account-level Graph API calls (message templates, phone number listing).",
                max_length=64,
            ),
        ),
    ]
