# Generated by Django 5.0.9 on 2026-06-22 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "current_flow",
                    models.CharField(
                        choices=[
                            ("main_menu", "Main Menu"),
                            ("registration", "Registration"),
                            ("past_paper", "Past Paper"),
                            ("revision", "Revision"),
                            ("quiz", "Quiz"),
                            ("ai_tutor", "AI Tutor"),
                            ("study_plan", "Study Plan"),
                            ("progress", "Progress"),
                        ],
                        default="main_menu",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone_number"], name="conversatio_phone_n_76e345_idx"
                    )
                ],
            },
        ),
    ]
