# Generated by Django 5.0.9 on 2026-06-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationstate",
            name="current_flow",
            field=models.CharField(
                choices=[
                    ("main_menu", "Main Menu"),
                    ("registration", "Registration"),
                    ("past_paper", "Past Paper"),
                    ("revision", "Revision"),
                    ("quiz", "Quiz"),
                    ("ai_tutor", "AI Tutor"),
                    ("study_plan", "Study Plan"),
                    ("progress", "Progress"),
                    ("billing", "Billing"),
                ],
                default="main_menu",
                max_length=20,
            ),
        ),
    ]
