# Generated by Django 5.2.15 on 2026-09-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tutor", "0002_plaintext_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprovider",
            name="model_name",
            field=models.CharField(default="gemini-3.6-flash", max_length=100),
        ),
    ]
